// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN1rMnCTwBZNXldwN3rW0hRIHan_Gl4L8',
    appId: '1:934810908369:android:97742a569985daf73437f0',
    messagingSenderId: '934810908369',
    projectId: 'admob-example-8e376',
    databaseURL: 'https://admob-example-8e376.firebaseio.com',
    storageBucket: 'admob-example-8e376.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc_KmpCwU3i-8_cBzv8uQkp1P7jxYaBGk',
    appId: '1:934810908369:ios:3c47dc9116ac4dbb3437f0',
    messagingSenderId: '934810908369',
    projectId: 'admob-example-8e376',
    databaseURL: 'https://admob-example-8e376.firebaseio.com',
    storageBucket: 'admob-example-8e376.appspot.com',
    iosClientId: '934810908369-k8912tpld6d1tslt1r8105vbinenchk8.apps.googleusercontent.com',
    iosBundleId: 'com.testing.cicd.cicd',
  );
}
