default_platform(:ios)

platform :ios do
  desc "Deploy iOS to Firebase App Distribution"
  lane :deploy_ios do |options|
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
      export_options: {
        uploadBitcode: false,
        uploadSymbols: true,
        compileBitcode: true
      }
    )
    firebase_app_distribution(
      app: ENV["FIREBASE_IOS_APP_ID"] || options[:firebase_ios_app_id],
      firebase_cli_token: options[:firebase_token] || ENV["FIREBASE_TOKEN"],
      groups: "internal-testers",
      release_notes: options[:release_notes]
    )
  end
end

platform :android do
  desc "Deploy Android to Firebase App Distribution"
  lane :deploy_android do |options|
    gradle(
      task: "assemble",
      build_type: "Release"
    )
    firebase_app_distribution(
      app: ENV["FIREBASE_ANDROID_APP_ID"] || options[:firebase_android_app_id],
      firebase_cli_token: options[:firebase_token] || ENV["FIREBASE_TOKEN"],
      groups: "internal-testers",
      release_notes: options[:release_notes]
    )
  end
end