name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy_android:
    runs-on: macos-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Build Android APK
        run: flutter build apk --release

      - name: Deploy Android to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_ANDROID_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          apkPath: build/app/outputs/flutter-apk/app-release.apk
