name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: macos-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Android APK
        run: flutter build apk --release

      - name: Build iOS archive
        run: flutter build ios --release --no-codesign

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy Android to Firebase App Distribution
        run: firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk --app ${{ secrets.FIREBASE_ANDROID_APP_ID }} --token ${{ secrets.FIREBASE_TOKEN }}

      - name: Deploy iOS to Firebase App Distribution
        run: firebase appdistribution:distribute "build/ios/archive/Runner.xcarchive/Products/Applications/Runner.app" --app ${{ secrets.FIREBASE_IOS_APP_ID }} --token ${{ secrets.FIREBASE_TOKEN }}
